### ISSUE TITLE
Update to Laravel 9

### ISSUE THREAD

**Issue by markc** [alphayowakarindi/Laravel-8-Blog-Tutorial-up-to-Deployment#1]
Any chance you could do this again with Laravel 9, Inertia, Vue3 and Tailwind?

**Comment by alphayowakarindi** [comment]
Hi Mark, yes and probably. I had already planned to redo it soon with Laravel 9, Vue3, and vanilla CSS. I'm not sure at the moment if I'll redo it with Inertia and Tailwind as well.

**Comment by markc** [comment]
Sorry to post on a closed issue, but I missed the notification for your response. FWIW, I think it would be a fairly simple "port" to Inertia, and I'd be happy to help where I can. The world needs a decent LIVT version of WordPress, or something that could become so.
